---
# TLS Secrets for ingress
kind: Secret
apiVersion: v1
metadata:
  name: ingress-tls
  namespace: tekton-pipelines
type: kubernetes.io/tls
data:
  tls.crt: |
    ${templateVariables[__SSL_SERVER_CERT_B64__]}
  tls.key: |
    ${templateVariables[__SSL_SERVER_KEY_B64__]}
