# This definition needs to deployed using kubeapply.sh
# bash setup/config/kubeapply.sh Secrets.yml
---
########################################
# Namespace for pipeline.
kind: Namespace
apiVersion: v1
metadata:
  name: pipeline
  labels:
    name: pipeline

---
########################################
# Git SSH authentication with the ssh-auth type.
kind: Secret
apiVersion: v1
type: kubernetes.io/ssh-auth
metadata:
  name: git-ssh-key
  namespace: pipeline
  annotations:
    tekton.dev/git-0: github.com
data:
  ssh-privatekey: ${templateVariables[__GIT_SSH_PRIVATE_KEY__]}

---
########################################
# Docker registry basic authentication with the dockerconfigjson type.
kind: Secret
apiVersion: v1
type: kubernetes.io/dockerconfigjson
metadata:
  name: registry-dockerconfigjson-auth
  namespace: pipeline
  annotations:
    tekton.dev/docker-0: https://registry.jerra.io
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LmplcnJhLmlvIjp7InVzZXJuYW1lIjoicmVnaXN0cnlfdXNlciIsInBhc3N3b3JkIjoiVGhpc0lzVGhlUmVnaXN0cnlQYXNzd29yZCIsImF1dGgiOiJjbVZuYVhOMGNubGZkWE5sY2pwVWFHbHpTWE5VYUdWU1pXZHBjM1J5ZVZCaGMzTjNiM0prIn19fQ==

---
########################################
# Docker registry basic authentication with the basic auth-type.
kind: Secret
apiVersion: v1
type: kubernetes.io/basic-auth
metadata:
  name: registry-basic-auth
  namespace: pipeline
  annotations:
    tekton.dev/docker-0: https://registry.jerra.io
stringData:
  username: ${templateVariables[__REGISTRY_USERNAME__]}
  password: ${templateVariables[__REGISTRY_PASSWORD__]}
