---
# Namespace
kind: Namespace
apiVersion: v1
metadata:
  name: dev-application
  labels:
    name: dev-application

---
# Service
kind: Service
apiVersion: v1
metadata:
  name: web-server
  namespace: dev-application
spec:
  selector:
    app: web-server
  type: ClusterIP
  ports:
    - name: http
      port: 10000
      targetPort: 10000

---
# Ingress
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: web-server
  namespace: dev-application
spec:
  tls:
    - secretName: ingress-tls
  rules:
    - host: web-server.jerra.io
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: web-server
                port:
                  number: 10000

---
# Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-server
  namespace: dev-application
spec:
  selector:
    matchLabels:
      app: web-server
  replicas: 1
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image:
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 10000
